services:
  - type: web
    name: on-call-bot
    env: node
    plan: starter # free will sleep; starter keeps it awake
    region: oregon # or frankfurt if your team is EU-based
    runtime: node # Render’s Node environment
    nodeVersion: 20
    buildCommand: |
      corepack enable
      corepack prepare yarn@latest --activate
      yarn install --frozen-lockfile
      yarn build
    startCommand: yarn start
    autoDeploy: true
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 # Render will override this; safe default
