services:
  - type: web
    name: on-call-bot
    env: node
    plan: starter # free will sleep; starter keeps it awake
    region: oregon # or frankfurt if your team is EU-based
    runtime: node # Render’s Node environment
    nodeVersion: 20
    buildCommand: |
      corepack enable
      corepack prepare pnpm@latest --activate
      pnpm install --frozen-lockfile
      pnpm build
    startCommand: pnpm start
    autoDeploy: true
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000 # Render will override this; safe default
      - key: SLACK_BOT_TOKEN
        fromSecret: slack-bot-token
      - key: SLACK_SIGNING_SECRET
        fromSecret: slack-signing-secret
      - key: OPENAI_API_KEY
        fromSecret: openai-api-key
      - key: SENTRY_WEBHOOK_SECRET
        fromSecret: sentry-webhook-secret
      - key: GITLAB_WEBHOOK_SECRET
        fromSecret: gitlab-webhook-secret
